/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/404': RouteRecordInfo<
      '/404',
      '/404',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/': RouteRecordInfo<
      '/about/',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/site': RouteRecordInfo<
      '/about/site',
      '/about/site',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/archives/': RouteRecordInfo<
      '/archives/',
      '/archives',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/categories/': RouteRecordInfo<
      '/categories/',
      '/categories',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/links/': RouteRecordInfo<
      '/links/',
      '/links',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/links/navigation': RouteRecordInfo<
      '/links/navigation',
      '/links/navigation',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/page/[page]': RouteRecordInfo<
      '/page/[page]',
      '/page/:page',
      { page: ParamValue<true> },
      { page: ParamValue<false> },
      | never
    >,
    '/posts/': RouteRecordInfo<
      '/posts/',
      '/posts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/docker-s': RouteRecordInfo<
      '/posts/docker-s',
      '/posts/docker-s',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/efficiency-dev': RouteRecordInfo<
      '/posts/efficiency-dev',
      '/posts/efficiency-dev',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/elastic-search': RouteRecordInfo<
      '/posts/elastic-search',
      '/posts/elastic-search',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/electron-note': RouteRecordInfo<
      '/posts/electron-note',
      '/posts/electron-note',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/fragment-a': RouteRecordInfo<
      '/posts/fragment-a',
      '/posts/fragment-a',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/java-concurrency': RouteRecordInfo<
      '/posts/java-concurrency',
      '/posts/java-concurrency',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/java-concurrencyTool': RouteRecordInfo<
      '/posts/java-concurrencyTool',
      '/posts/java-concurrencyTool',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/java-jmm': RouteRecordInfo<
      '/posts/java-jmm',
      '/posts/java-jmm',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/java-monitor': RouteRecordInfo<
      '/posts/java-monitor',
      '/posts/java-monitor',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/java-threadPool': RouteRecordInfo<
      '/posts/java-threadPool',
      '/posts/java-threadPool',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/javase-mianshi': RouteRecordInfo<
      '/posts/javase-mianshi',
      '/posts/javase-mianshi',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/mysql-backup': RouteRecordInfo<
      '/posts/mysql-backup',
      '/posts/mysql-backup',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/mysql-IdxCreateDesgRule': RouteRecordInfo<
      '/posts/mysql-IdxCreateDesgRule',
      '/posts/mysql-IdxCreateDesgRule',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/mysql-IdxDataStruct': RouteRecordInfo<
      '/posts/mysql-IdxDataStruct',
      '/posts/mysql-IdxDataStruct',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/mysql-lock': RouteRecordInfo<
      '/posts/mysql-lock',
      '/posts/mysql-lock',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/mysql-masterSlave': RouteRecordInfo<
      '/posts/mysql-masterSlave',
      '/posts/mysql-masterSlave',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/mysql-mianshi': RouteRecordInfo<
      '/posts/mysql-mianshi',
      '/posts/mysql-mianshi',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/mysql-mvcc': RouteRecordInfo<
      '/posts/mysql-mvcc',
      '/posts/mysql-mvcc',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/mysql-otherDbLog': RouteRecordInfo<
      '/posts/mysql-otherDbLog',
      '/posts/mysql-otherDbLog',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/mysql-Transaction': RouteRecordInfo<
      '/posts/mysql-Transaction',
      '/posts/mysql-Transaction',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/rabbitmq-a': RouteRecordInfo<
      '/posts/rabbitmq-a',
      '/posts/rabbitmq-a',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/redis-actualCombat': RouteRecordInfo<
      '/posts/redis-actualCombat',
      '/posts/redis-actualCombat',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/redis-basic': RouteRecordInfo<
      '/posts/redis-basic',
      '/posts/redis-basic',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/spring-cloud': RouteRecordInfo<
      '/posts/spring-cloud',
      '/posts/spring-cloud',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/spring-mj': RouteRecordInfo<
      '/posts/spring-mj',
      '/posts/spring-mj',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/uniapp-dev': RouteRecordInfo<
      '/posts/uniapp-dev',
      '/posts/uniapp-dev',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/vue3-project': RouteRecordInfo<
      '/posts/vue3-project',
      '/posts/vue3-project',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/vue3-s': RouteRecordInfo<
      '/posts/vue3-s',
      '/posts/vue3-s',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/xiaoxi-socket': RouteRecordInfo<
      '/posts/xiaoxi-socket',
      '/posts/xiaoxi-socket',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/xxl-job': RouteRecordInfo<
      '/posts/xxl-job',
      '/posts/xxl-job',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tags/': RouteRecordInfo<
      '/tags/',
      '/tags',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'node_modules/.pnpm/valaxy-theme-yun@0.26.10_vue@3.5.22_typescript@5.8.3_/node_modules/valaxy-theme-yun/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'node_modules/.pnpm/valaxy@0.26.10_@babel+parse_956a37322bc3e0ff7cb3e0ba6ce21830/node_modules/valaxy/client/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
    }
    'pages/404.md': {
      routes:
        | '/404'
      views:
        | never
    }
    'pages/about/index.md': {
      routes:
        | '/about/'
      views:
        | never
    }
    'pages/about/site.md': {
      routes:
        | '/about/site'
      views:
        | never
    }
    'pages/archives/index.md': {
      routes:
        | '/archives/'
      views:
        | never
    }
    'pages/categories/index.md': {
      routes:
        | '/categories/'
      views:
        | never
    }
    'pages/links/index.md': {
      routes:
        | '/links/'
      views:
        | never
    }
    'pages/links/navigation.md': {
      routes:
        | '/links/navigation'
      views:
        | never
    }
    'node_modules/.pnpm/valaxy-theme-yun@0.26.10_vue@3.5.22_typescript@5.8.3_/node_modules/valaxy-theme-yun/pages/page/[page].vue': {
      routes:
        | '/page/[page]'
      views:
        | never
    }
    'node_modules/.pnpm/valaxy-theme-yun@0.26.10_vue@3.5.22_typescript@5.8.3_/node_modules/valaxy-theme-yun/pages/posts/index.vue': {
      routes:
        | '/posts/'
      views:
        | never
    }
    'pages/posts/docker-s.md': {
      routes:
        | '/posts/docker-s'
      views:
        | never
    }
    'pages/posts/efficiency-dev.md': {
      routes:
        | '/posts/efficiency-dev'
      views:
        | never
    }
    'pages/posts/elastic-search.md': {
      routes:
        | '/posts/elastic-search'
      views:
        | never
    }
    'pages/posts/electron-note.md': {
      routes:
        | '/posts/electron-note'
      views:
        | never
    }
    'pages/posts/fragment-a.md': {
      routes:
        | '/posts/fragment-a'
      views:
        | never
    }
    'pages/posts/java-concurrency.md': {
      routes:
        | '/posts/java-concurrency'
      views:
        | never
    }
    'pages/posts/java-concurrencyTool.md': {
      routes:
        | '/posts/java-concurrencyTool'
      views:
        | never
    }
    'pages/posts/java-jmm.md': {
      routes:
        | '/posts/java-jmm'
      views:
        | never
    }
    'pages/posts/java-monitor.md': {
      routes:
        | '/posts/java-monitor'
      views:
        | never
    }
    'pages/posts/java-threadPool.md': {
      routes:
        | '/posts/java-threadPool'
      views:
        | never
    }
    'pages/posts/javase-mianshi.md': {
      routes:
        | '/posts/javase-mianshi'
      views:
        | never
    }
    'pages/posts/mysql-backup.md': {
      routes:
        | '/posts/mysql-backup'
      views:
        | never
    }
    'pages/posts/mysql-IdxCreateDesgRule.md': {
      routes:
        | '/posts/mysql-IdxCreateDesgRule'
      views:
        | never
    }
    'pages/posts/mysql-IdxDataStruct.md': {
      routes:
        | '/posts/mysql-IdxDataStruct'
      views:
        | never
    }
    'pages/posts/mysql-lock.md': {
      routes:
        | '/posts/mysql-lock'
      views:
        | never
    }
    'pages/posts/mysql-masterSlave.md': {
      routes:
        | '/posts/mysql-masterSlave'
      views:
        | never
    }
    'pages/posts/mysql-mianshi.md': {
      routes:
        | '/posts/mysql-mianshi'
      views:
        | never
    }
    'pages/posts/mysql-mvcc.md': {
      routes:
        | '/posts/mysql-mvcc'
      views:
        | never
    }
    'pages/posts/mysql-otherDbLog.md': {
      routes:
        | '/posts/mysql-otherDbLog'
      views:
        | never
    }
    'pages/posts/mysql-Transaction.md': {
      routes:
        | '/posts/mysql-Transaction'
      views:
        | never
    }
    'pages/posts/rabbitmq-a.md': {
      routes:
        | '/posts/rabbitmq-a'
      views:
        | never
    }
    'pages/posts/redis-actualCombat.md': {
      routes:
        | '/posts/redis-actualCombat'
      views:
        | never
    }
    'pages/posts/redis-basic.md': {
      routes:
        | '/posts/redis-basic'
      views:
        | never
    }
    'pages/posts/spring-cloud.md': {
      routes:
        | '/posts/spring-cloud'
      views:
        | never
    }
    'pages/posts/spring-mj.md': {
      routes:
        | '/posts/spring-mj'
      views:
        | never
    }
    'pages/posts/uniapp-dev.md': {
      routes:
        | '/posts/uniapp-dev'
      views:
        | never
    }
    'pages/posts/vue3-project.md': {
      routes:
        | '/posts/vue3-project'
      views:
        | never
    }
    'pages/posts/vue3-s.md': {
      routes:
        | '/posts/vue3-s'
      views:
        | never
    }
    'pages/posts/xiaoxi-socket.md': {
      routes:
        | '/posts/xiaoxi-socket'
      views:
        | never
    }
    'pages/posts/xxl-job.md': {
      routes:
        | '/posts/xxl-job'
      views:
        | never
    }
    'pages/tags/index.md': {
      routes:
        | '/tags/'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
