/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    '/about/': RouteRecordInfo<'/about/', '/about', Record<never, never>, Record<never, never>>,
    '/about/site': RouteRecordInfo<'/about/site', '/about/site', Record<never, never>, Record<never, never>>,
    '/archives/': RouteRecordInfo<'/archives/', '/archives', Record<never, never>, Record<never, never>>,
    '/categories/': RouteRecordInfo<'/categories/', '/categories', Record<never, never>, Record<never, never>>,
    '/links/': RouteRecordInfo<'/links/', '/links', Record<never, never>, Record<never, never>>,
    '/links/navigation': RouteRecordInfo<'/links/navigation', '/links/navigation', Record<never, never>, Record<never, never>>,
    '/page/[page]': RouteRecordInfo<'/page/[page]', '/page/:page', { page: ParamValue<true> }, { page: ParamValue<false> }>,
    '/posts/': RouteRecordInfo<'/posts/', '/posts', Record<never, never>, Record<never, never>>,
    '/posts/docker-s': RouteRecordInfo<'/posts/docker-s', '/posts/docker-s', Record<never, never>, Record<never, never>>,
    '/posts/efficiency-dev': RouteRecordInfo<'/posts/efficiency-dev', '/posts/efficiency-dev', Record<never, never>, Record<never, never>>,
    '/posts/elastic-search': RouteRecordInfo<'/posts/elastic-search', '/posts/elastic-search', Record<never, never>, Record<never, never>>,
    '/posts/fragment-a': RouteRecordInfo<'/posts/fragment-a', '/posts/fragment-a', Record<never, never>, Record<never, never>>,
    '/posts/java-threadPool': RouteRecordInfo<'/posts/java-threadPool', '/posts/java-threadPool', Record<never, never>, Record<never, never>>,
    '/posts/javase-mianshi': RouteRecordInfo<'/posts/javase-mianshi', '/posts/javase-mianshi', Record<never, never>, Record<never, never>>,
    '/posts/mysql-aa': RouteRecordInfo<'/posts/mysql-aa', '/posts/mysql-aa', Record<never, never>, Record<never, never>>,
    '/posts/mysql-lock': RouteRecordInfo<'/posts/mysql-lock', '/posts/mysql-lock', Record<never, never>, Record<never, never>>,
    '/posts/mysql-mianshi': RouteRecordInfo<'/posts/mysql-mianshi', '/posts/mysql-mianshi', Record<never, never>, Record<never, never>>,
    '/posts/rabbitmq-a': RouteRecordInfo<'/posts/rabbitmq-a', '/posts/rabbitmq-a', Record<never, never>, Record<never, never>>,
    '/posts/spring-cloud': RouteRecordInfo<'/posts/spring-cloud', '/posts/spring-cloud', Record<never, never>, Record<never, never>>,
    '/posts/spring-mj': RouteRecordInfo<'/posts/spring-mj', '/posts/spring-mj', Record<never, never>, Record<never, never>>,
    '/posts/vue3-project': RouteRecordInfo<'/posts/vue3-project', '/posts/vue3-project', Record<never, never>, Record<never, never>>,
    '/posts/vue3-s': RouteRecordInfo<'/posts/vue3-s', '/posts/vue3-s', Record<never, never>, Record<never, never>>,
    '/posts/xiaoxi-socket': RouteRecordInfo<'/posts/xiaoxi-socket', '/posts/xiaoxi-socket', Record<never, never>, Record<never, never>>,
    '/posts/xxl-job': RouteRecordInfo<'/posts/xxl-job', '/posts/xxl-job', Record<never, never>, Record<never, never>>,
    '/tags/': RouteRecordInfo<'/tags/', '/tags', Record<never, never>, Record<never, never>>,
  }
}
